### ISSUE TITLE
Lack of index.html?

### ISSUE THREAD

**Issue by teamen** [SolidZORO/nighte#1]
Hi. When i run the project in local, it does not generate an index.html and an undefined folder was created in the `OUTPUT_HTML_DIR` directory, as shown below.
![image](https://user-images.githubusercontent.com/13899144/29522695-aa0c9712-86bc-11e7-9b98-fbb985c3e826.png)

**Comment by SolidZORO** [comment]
pls tell me more info.

show your project's _blog DIR and terminal error info.

now, i have updated nighte's README, you can try.

**Comment by SolidZORO** [comment]
and now, i fixed build empty undefined and i added `sample.md`. https://github.com/SolidZORO/nighte/commit/e87d36934ba7260d4e1d31dde9fe1f5aa4ea56b3
